package com.NTPWS.projekt.model.enums;

public enum MessageTypes {
    PRIVATE_MESSAGE, GROUP_MESSAGE, CLIENT_ID, NEW_MESSAGE, NEW_GROUP, OFFER, ANSWER, ICE_CANDIDATE, NEW_EVENT, NEW_COMMENT, DELETE_EVENT, END_CALL
}
